import '../models/movie.dart';


  List<Movie> movies = [
    Movie(
      id: '1',
      title: 'Inception',
      director: 'Christopher Nolan',
      releaseYear: 2010,
      genres: ['Sci-Fi', 'Thriller'],
      description: 'A thief steals corporate secrets using dream-sharing technology.',
      rating: 8.8,
      posterUrl: 'assets/images/1.jpeg',
    ),
    Movie(
      id: '2',
      title: 'The Shawshank Redemption',
      director: 'Frank Darabont',
      releaseYear: 1994,
      genres: ['Drama'],
      description: 'Two imprisoned men bond over a number of years.',
      rating: 9.3,
      posterUrl: 'assets/images/2.jpg',
    ),
    Movie(
      id: '3',
      title: 'The Dark Knight',
      director: 'Christopher Nolan',
      releaseYear: 2008,
      genres: ['Action', 'Drama'],
      description: 'Batman faces the Joker, a criminal mastermind.',
      rating: 9.0,
      posterUrl: 'assets/images/3.jpeg',
    ),
    Movie(
      id: '4',
      title: 'Interstellar',
      director: 'Christopher Nolan',
      releaseYear: 2014,
      genres: ['Sci-Fi', 'Drama'],
      description: 'A team travels through a wormhole in space to save humanity.',
      rating: 8.6,
      posterUrl: 'assets/images/4.jpg',
    ),
    Movie(
      id: '5',
      title: 'Forrest Gump',
      director: 'Robert Zemeckis',
      releaseYear: 1994,
      genres: ['Drama', 'Romance'],
      description: 'The story of a man with a low IQ achieving incredible things.',
      rating: 8.8,
      posterUrl: 'assets/images/5.jpg',
    ),
    Movie(
      id: '6',
      title: 'The Matrix',
      director: 'The Wachowskis',
      releaseYear: 1999,
      genres: ['Sci-Fi', 'Action'],
      description: 'A hacker learns the truth about his reality and his role in a war.',
      rating: 8.7,
      posterUrl: 'assets/images/6.jpeg',
    ),
    Movie(
      id: '7',
      title: 'Gladiator',
      director: 'Ridley Scott',
      releaseYear: 2000,
      genres: ['Action', 'Drama'],
      description: 'A betrayed Roman general seeks revenge.',
      rating: 8.5,
      posterUrl: 'assets/images/7.jpeg',
    ),
    Movie(
      id: '8',
      title: 'Titanic',
      director: 'James Cameron',
      releaseYear: 1997,
      genres: ['Romance', 'Drama'],
      description: 'A love story unfolds on the ill-fated Titanic.',
      rating: 7.9,
      posterUrl: 'assets/images/8.jpg',
    ),
    Movie(
      id: '9',
      title: 'Avengers: Endgame',
      director: 'Anthony and Joe Russo',
      releaseYear: 2019,
      genres: ['Action', 'Sci-Fi'],
      description: 'The Avengers assemble to reverse the actions of Thanos.',
      rating: 8.4,
      posterUrl: 'assets/images/9.jpg',
    ),
    Movie(
      id: '10',
      title: 'The Godfather',
      director: 'Francis Ford Coppola',
      releaseYear: 1972,
      genres: ['Crime', 'Drama'],
      description: 'The aging patriarch of an organized crime dynasty transfers control.',
      rating: 9.2,
      posterUrl: 'assets/images/10.jpg',
    ),
    Movie(
      id: '11',
      title: 'Pulp Fiction',
      director: 'Quentin Tarantino',
      releaseYear: 1994,
      genres: ['Crime', 'Drama'],
      description: 'The lives of two mob hitmen intertwine in unexpected ways.',
      rating: 8.9,
      posterUrl: 'assets/images/11.jpeg',
    ),
    Movie(
      id: '12',
      title: 'Jurassic Park',
      director: 'Steven Spielberg',
      releaseYear: 1993,
      genres: ['Adventure', 'Sci-Fi'],
      description: 'A theme park with cloned dinosaurs faces a major security failure.',
      rating: 8.1,
      posterUrl: 'assets/images/12.jpg',
    ),
    Movie(
      id: '13',
      title: 'The Lion King',
      director: 'Roger Allers and Rob Minkoff',
      releaseYear: 1994,
      genres: ['Animation', 'Drama'],
      description: 'A young lion prince flees his kingdom only to learn his destiny.',
      rating: 8.5,
      posterUrl: 'assets/images/13.jpg',
    ),
  ];


